name: Publish to GPR
description: Publish gem to GPR

inputs:
  gem_host_api_key:
    description: GEM host API key
    required: true

runs:
  using: composite
  steps:
    - name: Publish to GPR
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        GEM_HOST_API_KEY: ${{ inputs.gem_host_api_key }}
        OWNER: ${{ github.repository_owner }}
